### ISSUE TITLE
Roxygen Headers Using @import

### ISSUE THREAD

**Issue by azheng26** [tito1224/GLMM#11]
I see that you have added @import for multiple whole packages. I believe that Professor Simon Bonner told us not to do that because the user may get a warning for functions that may have the same name. I think we should use @importFrom and choose specific functions from those packages that we're using in the R files. Let me know if you agree, I am afraid that he will deduct marks for not using @importFrom instead of @import !

**Comment by tito1224** [comment]
hey agree! I've changed it up in the code lmk what you think :)

**Comment by azheng26** [comment]
Issue resolved!
