### ISSUE TITLE
Double check how sourcing works 

### ISSUE THREAD

**Issue by tito1224** [tito1224/GLMM#6]
- getting an error when i use source in confidenceinterval.R file

**Comment by tito1224** [comment]
@azheng26 do we include the library() command in the .R script? or do we just keep the import files

**Comment by azheng26** [comment]
If we keep library(), i's not guaranteed that the user will already have the package installed so I believe that @ import will handle this issue. We can delete library().

**Comment by tito1224** [comment]
ok awesome ty!!
